### ISSUE TITLE
[Admin/ Cazuri/ Documente] wrong behavior for "Încarcă document" button from the Documente card in the case overview

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/sunrise#102]
Current behavior: When the user click on the "Încarcă document" button from the Documente card in the case overview, it takes the user to the "Documente" page. 

Expected behavior: When the user click on the "Încarcă document" button from the Documente card in the case overview, it should open the "Adauga document" modal screen. When the user saves the document, it should redirect them to that document's page.  

![Image](https://github.com/user-attachments/assets/147fe89c-9b8f-4504-a52a-05051591f076)

**Comment by alexPopaCode4** [comment]
after merge #118 and #105
