### ISSUE TITLE
[Admin/ Cazuri/ Informatii caz/ Agresori] implement sub-heading if more than 1 aggressor

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/sunrise#110]
Implement sub-headings if more than 1 aggressor
[Design in view mode](https://www.figma.com/design/gpOGCkb9B6pTfe1DvleVMm/Sunrise?node-id=6685-10821&t=xRAyliGagXUBb1eS-4)
[Design in edit mode
](https://www.figma.com/design/gpOGCkb9B6pTfe1DvleVMm/Sunrise?node-id=4825-15295&t=xRAyliGagXUBb1eS-4)

**Comment by alexPopaCode4** [comment]
- [ ] view personal information tab label
- [ ] view personal information section heading
- [ ] create new case - repeater heading
