### ISSUE TITLE
[General] Change the tag components used for displaying in view mode the values of multiple select fields

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/sunrise#111]
Currently, the selected values of multiple select fields are displayed in view mode using the tags component (see example below). 
Expected behavior: the selected values of multiple select fields should be displayed in view mode as text ([see design here](https://www.figma.com/design/gpOGCkb9B6pTfe1DvleVMm/Sunrise?node-id=5573-8355&t=xRAyliGagXUBb1eS-4)).
The rule applies for all cases across the platform. 

![Image](https://github.com/user-attachments/assets/d62b248f-9a02-4b9b-928b-eab06aee944f)

**Comment by alexPopaCode4** [comment]
fix for team section in #105
