### ISSUE TITLE
[Evaluation] Create wizard for evaluation of a case (New case)

### ISSUE THREAD

**Issue by overeha** [code4romania/sunrise#14]
**User Story**
As an NGO user, I want to be able to input details about a case with the support of a wizard that guides me through each phase of the Evaluation.  

--------

**Description**
New case: 
Once I logged in a new case, in the initial evaluation section I want to be able to access a wizard that guides me through six different sections where I can input data about a case. 

- The wizard does not have to be completed for the evaluation to be recorded. The data should be saved after each step of the evaluation. 
- I have to be able to navigate back and fourth through the evaluation wizard phases at every moment in the process. 

- The first phase of the Evaluation is a section containing data related to the case registration. ([Figma here](https://www.figma.com/file/gpOGCkb9B6pTfe1DvleVMm/Sunrise?type=design&node-id=5573-8477&mode=design&t=jjsUvZzUXaTyQ75j-4)). Some of the data in this section is pre-populated from the case identification information already in the system. 

- The second phase of the Evaluation is “Violenta”. As a user I want to be able to input the required data as displayed on this screen ([Figma here](https://www.figma.com/file/gpOGCkb9B6pTfe1DvleVMm/Sunrise?type=design&node-id=5573-8790&mode=design&t=jjsUvZzUXaTyQ75j-4))

- The third phase of the Evaluation is “Factori de risc”. As a user I want to be able to input the required data as displayed on this screen. ([Figma here](https://www.figma.com/file/gpOGCkb9B6pTfe1DvleVMm/Sunrise?type=design&node-id=5573-9171&mode=design&t=jjsUvZzUXaTyQ75j-4)]

- The fourth phase of the Evaluation is “Servicii solicitate”. As a user I want to be able to input the required data as displayed on this screen. ([Figma here](https://www.figma.com/file/gpOGCkb9B6pTfe1DvleVMm/Sunrise?type=design&node-id=5573-9945&mode=design&t=jjsUvZzUXaTyQ75j-4)) The data is multiple select as per the Data dictionary. 

- The fifth phase of the Evaluation is “Situatia beneficiarilor”. As a user I want to be able to input the required data as displayed on this screen. ([Figma here](https://www.figma.com/file/gpOGCkb9B6pTfe1DvleVMm/Sunrise?type=design&node-id=5573-10506&mode=design&t=jjsUvZzUXaTyQ75j-4)) 

In order to save the information, as a user I have to click on “Pasul urmator”
If I have reached the last step of the wizard, I will click on “Finalizeaza”. 

--------

**Main Flow**
1. Go to Cases
2. Select a case
3. Click on “Incepe evaluarea” in the dedicated section
4. Fill in the information in each step of the wizard. 
5. Click on “Pasul urmator”

- [Figma flow start  here](https://www.figma.com/file/gpOGCkb9B6pTfe1DvleVMm/Sunrise?type=design&node-id=5573-8477&mode=design&t=jjsUvZzUXaTyQ75j-4) 
- [Data Dictionary here](https://docs.google.com/spreadsheets/d/1CwWLNTUE7yhHBpwQXLC21Znl3rjrLuLmav1Vu-Go8Dc/edit#gid=0)

**Comment by andrabrinzaniuc** [comment]
I have added in the [Data Dictionary](https://docs.google.com/spreadsheets/d/1CwWLNTUE7yhHBpwQXLC21Znl3rjrLuLmav1Vu-Go8Dc/edit#gid=1344046261) the subheadings for the Factori de Risc section in Evaluare Initiala.

Subsection (H2): I. Istoricul violenței
Subsection (H2): II. Formele și tiparul violenței
Subsection (H2): III. Factori de risc legați de comportamentul agresorului
Subsection (H2): IV. Percepția victimei asupra riscului
Subsection (H2): V. Factori agravanți
Subsection (H2): VI. Suport social
