### ISSUE TITLE
Invalid Format Error for 13-Digit CNP

### ISSUE THREAD

**Issue by andrei-manda** [code4romania/sunrise#277]
#### Description

For a 13-digit CNP (e.g., 2850609123456), the system displays the error: “Câmpul DATA.CNP nu are un format valid.” 

#### Note

I was unable to find more than one valid CNP for this input.

![image](https://github.com/user-attachments/assets/be8cf70e-dc6e-4655-9f7f-db7db72cf460)

**Comment by teodoranegru** [comment]
Also, the inline error should be "Câmpul CNP nu are un format valid"

**Comment by alexmanase** [comment]
> For a 13-digit CNP (e.g., 2850609123456), the system displays the error: “Câmpul DATA.CNP nu are un format valid.”

That's because it's not a valid CNP. You can check here: https://cnpgenerator.ro/verificare-cnp
