### ISSUE TITLE
ID Displayed Instead of Name as a Valid Option in the Specialist List

### ISSUE THREAD

**Issue by andrei-manda** [code4romania/sunrise#291]
#### Description

The Specialist List display the admin user ID (17) instead of the name, as a preselected valid option. 
If the option is removed and the list is reopened, it does not reappear. 

https://github.com/user-attachments/assets/d2b0e062-37ca-477e-9dbb-9b74211a8f2f

![image](https://github.com/user-attachments/assets/955e89ea-9875-4e8e-9e79-6e1c9bc72bed)

**Comment by teodoranegru** [comment]
this is linked to the issue #266 - to address together
