### ISSUE TITLE
'Data nasterii' Input Shows Time Component Alongside Date

### ISSUE THREAD

**Issue by andrei-manda** [code4romania/sunrise#337]
#### Note

This issue occurs only on the 'Date Identitate' details page, as the Case Page displays the date correctly.

- URL: /org/_{center}_/cases/_{case_id}_/identity?tab=-identitate-beneficiar-tab

![image](https://github.com/user-attachments/assets/ca1fd7e2-ecf0-44d1-88d2-5f944bdcaa4c)

**Comment by teodoranegru** [comment]
**Remove seconds from time picker at add Sedinta/activitate**

**Comment by teodoranegru** [comment]
![Image](https://github.com/user-attachments/assets/a309922b-e288-462f-9f5e-06b256fa35c6)
