### ISSUE TITLE
General - Date picker does not close automatically when a date is selected

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/sunrise#357]
**Describe the bug**
When a user selects a date in the date picker component, the component remains open. The user must manually click outside the date picker to close it. This behavior is inconsistent with expected functionality, where the date picker should close automatically upon date selection.

**Expected behavior**
The date picker should close automatically after a date is selected.

**Comment by alexPopaCode4** [comment]
this issue was resolved in another pr
