### ISSUE TITLE
[General/ Staff] Update the display logic for the info text under the "Rol specialitate" field in the Staff section

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/sunrise#398]
If the selected role has Are acces la toate cazurile din Centru=TRUE as DEFAULT -> display "Acest tip de rol are acces _la toate cazurile din cadrul Centrului_, însă nu deține drepturi de administrare ale sistemului. Puteți oferi permisiuni suplimentare din lista de mai jos." 

If the selected role has Are acces la toate cazurile din Centru=FALSE as DEFAULT -> display "Acest tip de utilizator are acces _doar la cazurile din echipa cărora face parte_ și nu deține drepturi de administrare ale sistemului. Puteți oferi permisiuni suplimentare din lista de mai jos." 

![Image](https://github.com/user-attachments/assets/938cc87f-122a-4b8d-ae4b-c513eb9a94ce)

**Comment by andrabrinzaniuc** [comment]
@alexPopaCode4 - the message should NOT be displayed when no selection is made for role. The message should ONLY be displayed if one of the two conditions above = TRUE
