### ISSUE TITLE
[NGO Admin; Specialist/ Cazuri/ Plan de interventie] Implement new section/tab called "Planuri lunare"

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/sunrise#425]
**Description**

Implement in "Plan de interventie" page a tab named "Planuri lunare". In this tab, implement a table named "Planuri lunare", where the user can add monthly plans to the intervention plan.

**Flows**

Add plan

1. User navigates to Plan de interventie section, from the Case Overview page, within an Individual Beneficiary file
2. User clicks on the "Vezi detalii plan" button
3. System retrieves the "Plan de intervenție" page
4. User clicks on the "Planuri lunare" tab
5. User clicks on the "Crează un plan" button
IF IT IS THE FIRST MONTHLY PLAN IN THAT INTERVENTION PLAN -> 6.1. The system retrieves the "Creează plan lunar" screen ([link](https://www.figma.com/design/gpOGCkb9B6pTfe1DvleVMm/Sunrise?node-id=9643-15632&t=LLdSDx2jjU2qmQG5-4))
IF IT IS NOT THE FIRST MONTHLY PLAN IN THAT INTERVENTION PLAN -> 6.2.  The system retrieves the "Crează un plan lunar de intervenție nou" modal screen ([link](https://www.figma.com/design/gpOGCkb9B6pTfe1DvleVMm/Sunrise?node-id=9643-15904&t=LLdSDx2jjU2qmQG5-4)) (the section has the same behaviour as the one implemented for the monitoring file) 
7. User fills in the information about the plan
9. User clicks on "Crează plan" button
10. The system retrieves the "Plan de intervenție" page, "Planuri lunare" tab, displays the added plan in the table and the success message

Link to Figma: https://www.figma.com/design/gpOGCkb9B6pTfe1DvleVMm/Sunrise?node-id=9643-15307&t=LLdSDx2jjU2qmQG5-4

**Comment by andrabrinzaniuc** [comment]
@andrabrinzaniuc to update data dictionary with new variables

**Comment by andrabrinzaniuc** [comment]
@alexPopaCode4 [data dictionary](https://docs.google.com/spreadsheets/d/1CwWLNTUE7yhHBpwQXLC21Znl3rjrLuLmav1Vu-Go8Dc/edit?gid=714449041#gid=714449041) updated - lines 145-158, tab Plan de intervenție
