### ISSUE TITLE
[Admin/ Cazuri/ Înregistrare caz nou] wrong behavior for "Domiciliul legal al beneficiarului este și domiciliul efectiv" checkbox

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/sunrise#43]
**Current behavior:**
When the user ticks the "Domiciliul legal al beneficiarului este și domiciliul efectiv" checkbox, the fields _Județ domiciliu efectiv, Oraș/UAT domiciliu efectiv, Adresă domiciliu efectiv and Mediu rezidență domiciliu efectiv_ dissapear. 

**Expected behavior:** 
When the user ticks the "Domiciliul legal al beneficiarului este și domiciliul efectiv" the system should prefill the mentioned above fields with the values entered in the previous section (referring to legal residency) and make the fields disabled. If the user unticks the checkbox, the fields become clear and editable. 

![Image](https://github.com/code4romania/sunrise/assets/102228836/a44d5f22-f063-495f-8403-6c589d7559c6)

**Comment by alexPopaCode4** [comment]
In issue #8 we decide to hide fields for effective address.
Reason:
If you change legal address fields and "Domiciliul legal al beneficiarului este și domiciliul efectiv" is checked we don't sync again effective address in edit interface, just in db after save
