### ISSUE TITLE
[Admin/ Cazuri/ Evaluare inițială] bug at navigating to a previous step in the flow

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/sunrise#66]
**Describe the bug**
When you are in the Evaluare inițială flow and want to go back to a previous step, the form is not being displayed. (See video below)

https://github.com/code4romania/sunrise/assets/102228836/723c817b-709b-4a50-bad8-570aa42d4e4d

**Expected behavior**
The user should be able to navigate between steps of the flow and the information they had filled in should remain in the page.

**Comment by alexPopaCode4** [comment]
Fixed when update filament library
