### ISSUE TITLE
[Admin/ Cazuri/ Evaluare detaliată] wrong empty states for the sub-sections from the "Detalii evaluare" step

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/sunrise#82]
In the "Detalii evaluare" step/section, there are 2 sub-sections: "Specialiștii care au colaborat la realizarea evaluării" and "Întrevederi (sau convorbiri telefonice) pentru colectarea datelor"
Each of them behave as repeaters, the first one being a table where the user can add more rows, and the second one being a set of fields that can be duplicated. 
Currently, both of them have empty states that don't align with the design. 

Implement the following empty states:

1.  The "Specialiștii care au colaborat la realizarea evaluării" table should have one visible empty row plus the "Adaugă încă un rând" button 

2. The "Întrevederi (sau convorbiri telefonice) pentru colectarea datelor" sub-section should have one set of empty data fields plus the "Adaugă încă o întrevedere" button 

See the design below 

![Image](https://github.com/code4romania/sunrise/assets/102228836/00a82385-8b15-405e-a480-3aef2499cdb9)

**Comment by alexPopaCode4** [comment]
In filament defaultItems() for repeater work just on create page but technical, we use beneficiary edit pages  for each section (initial/detailed evaluation, team, documents etc)
@andreiio or @gheorghelupu17 you have any idea how tot do this?
