### ISSUE TITLE
[Admin/ Cazuri/ Echipa de caz] wrong behavior for Echipa de caz section

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/sunrise#91]
Current behavior: when the user creates a new case, the Echipa de caz section from that case is empty.  

Expected behavior: when the user creates a new case, the Echipa de caz section should contain the user who created the case. 
If that user can be a Manager de caz (role defined in the Staff section), then the user is automatically added as Manager the caz on that case. If the user can not be a Manager de caz, then the user is automatically added as Specialist. ([see more details in the design](https://www.figma.com/design/gpOGCkb9B6pTfe1DvleVMm/Sunrise?node-id=5684-7917&t=OJMinxtNtAH0S8gY-4))

**Comment by teodoranegru** [comment]
The role of the user who created the case is not displayed in the table. Review the behavior description [here] and implement it. (https://www.figma.com/design/gpOGCkb9B6pTfe1DvleVMm/Sunrise?node-id=5684-7917&t=xRAyliGagXUBb1eS-4)
![image](https://github.com/user-attachments/assets/2fd05ad4-d864-45cd-acae-1daa4cdca6c1)

**Comment by alexPopaCode4** [comment]
hello, this user hasn't any role associated. you can check this here https://sunrise.staging.heroesof.tech/org/kbad/users/2/edit

**Comment by teodoranegru** [comment]
> hello, this user hasn't any role associated. you can check this here https://sunrise.staging.heroesof.tech/org/kbad/users/2/edit

That is correct. However, I added a role for this user but it didn't update in the Echipa de caz section.

**Comment by alexPopaCode4** [comment]
we don't update role in team section when we change user roles :( 
i add new case and in team section role is assigned
